require './validate_events'
require './validate_people'
require './validate_projects'
require './validate_texts'
require './validate_twitter_keywords'
require './validate_jobs'
require './validate_courses'
require './validate_locations'
